services:
  demo:
    container_name: demodotnet
    image: demoauthentication
    build:
      context: .
      dockerfile: DemoAuthentication/Dockerfile
    ports: 
        - "8080:8080"
    volumes:
      - demovolume:/app
    depends_on:
      sqlserver: 
        condition: service_healthy
    networks:
      - demo
  sqlserver:
    container_name: sqlserver
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1435:1433"
    volumes:
      - sqlserver:/var/opt/mssql
    environment:
      SA_PASSWORD: Password12345@
      ACCEPT_EULA: Y
    networks:
      - demo
networks:
  demo: 
volumes:
  sqlserver:
  demovolume: