name: demo-authentication-deployment

on: 
  push:
    branches: 
      main

      
jobs:
  docker-compose: 
    runs-on: self-hosted
    environment: docker
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Run "docker compose db"
      run: docker compose up -d sqlserver
    - name: Run "docker compose build"
      run: docker compose up --build -d demo